title: Course Notebooks
html:
    theme:
        name: "sphinx_book_theme"
        options:
            default_mode: "light"
            theme_switcher: true
    extra_css:
        - custom_hide.css
    extra_js:
        - custom_toggle.js
sphinx:
    config:
        html_show_copyright: false
jupyter_execute_notebooks: "off"
execute:
    execute_notebooks: "off"
    allow_errors: false
    exclude_patterns: []
    timeout: 30
    stderr_output: remove
    stdout_output: remove
    remove_code_outputs: true

# Course display name mappings
course_display_names:
    "ray-101": "Ray 101"
    "anyscale_101": "Anyscale 101"
    "00_Developer_Intro_to_Ray": "Developer Intro to Ray"
